InventorySystemApplication/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventorySystemApplication.Data;
using InventorySystemApplication.Models;
using InventorySystemApplication.VMs;


namespace InventorySystemApplication.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
              return _context.CategoriesTable != null ? 
                          View(await _context.CategoriesTable.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.CategoriesTable'  is null.");
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CategoriesTable == null)
            {
                return NotFound();
            }

            var category = await _context.CategoriesTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Category_Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CategoriesTable == null)
            {
                return NotFound();
            }

            var category = await _context.CategoriesTable.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Category_Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CategoriesTable == null)
            {
                return NotFound();
            }

            var category = await _context.CategoriesTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CategoriesTable == null)
            {
                return Problem("Entity set 'ApplicationDbContext.CategoriesTable'  is null.");
            }
            var category = await _context.CategoriesTable.FindAsync(id);
            if (category != null)
            {
                _context.CategoriesTable.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.CategoriesTable?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InventorySystemApplication/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventorySystemApplication.Data;
using InventorySystemApplication.Models;
using InventorySystemApplication.VMs;


namespace InventorySystemApplication.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            
            List<ProductVM> objProduct = _context.ProductsTable.Select(n => new ProductVM{
                Id = n.Id,
                Product_Name= n.Product_Name,
                Manufacturing_Date = n.Manufacturing_Date,
                Expiry_Date = n.Expiry_Date,
                Category_Id = n.Category_Id,
                Categories = _context.CategoriesTable.FirstOrDefault(c => c.Id == n.Category_Id)
            }

            ).ToList();
              return View(objProduct);
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductsTable == null)
            {
                return NotFound();
            }

            var product = await _context.ProductsTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            var cat = _context.CategoriesTable.ToList();
            ViewBag.Categories= cat;
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Product_Name,Manufacturing_Date,Expiry_Date,Category_Id")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            

            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProductsTable == null)
            {
                return NotFound();
            }

            var product = await _context.ProductsTable.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var cat = _context.CategoriesTable.ToList();
            ViewBag.Categories = cat;
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Product_Name,Manufacturing_Date,Expiry_Date,Category_Id")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProductsTable == null)
            {
                return NotFound();
            }

            var product = await _context.ProductsTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProductsTable == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ProductsTable'  is null.");
            }
            var product = await _context.ProductsTable.FindAsync(id);
            if (product != null)
            {
                _context.ProductsTable.Remove(product);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
          return (_context.ProductsTable?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InventorySystemApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventorySystemApplication.Data;
using InventorySystemApplication.Models;
using InventorySystemApplication.VMs;


namespace InventorySystemApplication.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            List<UserVM> objUser = _context.UsersTable.Select(n => new UserVM {
                Id = n.Id,
                User_Name = n.User_Name,
                User_Email = n.User_Email,
                User_Telephone = n.User_Telephone,
                Warehouse_Id = n.Warehouse_Id,
                Password = n.Password,
                Warehouses = _context.WarehousesTable.Where(w => w.Id == n.Warehouse_Id).FirstOrDefault()
        }).ToList(); 
              return View(objUser);
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UsersTable == null)
            {
                return NotFound();
            }

            var user = await _context.UsersTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            var war = _context.WarehousesTable.ToList();
            ViewBag.Warehouses = war;
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User_Name,User_Email,User_Telephone,Warehouse_Id,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                SystemUser systemuser = new SystemUser {
                User_Id = user.Id,
                User_Name = user.User_Name ,
                User_Email = user.User_Email ,
                User_Telephone = user.User_Telephone ,
                Warehouse_Id = user.Warehouse_Id ,
                Password = user.Password
                };
                _context.SystemUsersTable.Add(systemuser);
                _context.Add(user);
                await _context.SaveChangesAsync();
                var use = _context.UsersTable.Where(n => n.User_Name == user.User_Name && n.Password == user.Password).FirstOrDefault();
                var sysUser = _context.SystemUsersTable.Where(n => n.User_Name == user.User_Name && n.Password == user.Password).FirstOrDefault();
                sysUser.User_Id = use.Id;
                _context.SystemUsersTable.Update(sysUser);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UsersTable == null)
            {
                return NotFound();
            }

            var user = await _context.UsersTable.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var war = _context.WarehousesTable.ToList();
            ViewBag.Warehouses = war;
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,User_Name,User_Email,User_Telephone,Warehouse_Id")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    List<SystemUser> systemUserObj = _context.SystemUsersTable.ToList();
                    if(systemUserObj != null)
                    {
                        foreach(var obj in systemUserObj)
                        {
                            if(obj.User_Id == user.Id)
                            {
                                obj.User_Name = user.User_Name;
                                obj.User_Email = user.User_Email;
                                obj.User_Telephone = user.User_Telephone;
                                obj.Warehouse_Id = user.Warehouse_Id;
                                obj.Password = user.Password;
                                
                                _context.SystemUsersTable.Update(obj);
                                break;
                            }; ;
                        }
                    }
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UsersTable == null)
            {
                return NotFound();
            }

            var user = await _context.UsersTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UsersTable == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UsersTable'  is null.");
            }
            var user = await _context.UsersTable.FindAsync(id);
            if (user != null)
            {
                _context.UsersTable.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.UsersTable?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InventorySystemApplication/Views/Menus/Admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Menu";
}
<!DOCTYPE html>
<html>
<head>
  <title>Home Menu</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f1f1f1;
      margin: 0;
      padding: 20px;
    }
    
    h1 {
      text-align: center;
    }
    
    .product-card {
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin-bottom: 20px;
      cursor: pointer;
      transition: transform 0.3s;
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }
    
    .product-card:hover {
      transform: scale(1.05);
    }
    
    .product-card i {
      font-size: 48px;
      color: #888;
      margin-bottom: 10px;
    }
    
    .product-card h2 {
      margin-top: 0;
    }
    
    .product-card p {
      color: #888;
      margin-top: 0;
    }
  </style>
</head>
<body>
  <h1>Menu</h1>
  
  <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Warehouses")'">
        <i class="fas fa-house"></i>
    <h2>Warehouses</h2>
    <p>Add,view and delete warehouses</p>
  </div>
  
  <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Category")'">
        <i class="fas fa-cubes"></i>
    <h2>Categories</h2>
    <p>Add, view and delete product categories</p>
  </div>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Product")'">
        <i class="fas fa-cube"></i>
    <h2>Products</h2>
    <p>Add,view and delete products</p>
  </div>
  
  <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "StockLevels")'">
        <i class="fas fa-bar-chart"></i>
    <h2>Stock Level</h2>
    <p>View available stock amount</p>
  </div>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Users")'">
        <i class="fas fa-users"></i>
    <h2>Users</h2>
    <p>Add,monitor and delete users</p>
  </div>
    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "WarehouseProducts")'">
        <i class="fas fa-university"></i>
        <h2>Warehouse Products</h2>
        <p>View all products in each warehouse</p>
    </div>
</body>
</html>

InventorySystemApplication/Views/Menus/Manager.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Menu";
}
<!DOCTYPE html>
<html>
<head>
  <title>Home Menu</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f1f1f1;
      margin: 0;
      padding: 20px;
    }
    
    h1 {
      text-align: center;
    }
    
    .product-card {
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      padding: 20px;
      margin-bottom: 20px;
      cursor: pointer;
      transition: transform 0.3s;
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }
    
    .product-card:hover {
      transform: scale(1.05);
    }
    
    .product-card i {
      font-size: 48px;
      color: #888;
      margin-bottom: 10px;
    }
    
    .product-card h2 {
      margin-top: 0;
    }
    
    .product-card p {
      color: #888;
      margin-top: 0;
    }
  </style>
</head>
<body>
  <h1>Menu</h1>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Product")'">
        <i class="fas fa-bar-chart"></i>
    <h2>Stock Level</h2>
    <p>View amount of stock in your warehouse</p>
  </div>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "Product")'">
        <i class="fas fa-cube"></i>
    <h2>Products</h2>
    <p>View all available products</p>
  </div>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "StockIns")'">
        <i class="fas fa-plus-circle"></i>
    <h2>Add Stock</h2>
    <p>Add stock in your warehouse</p>
  </div>

    <div class="product-card" onclick="window.location.href = '@Url.Action("Index", "StockTransfers")'">
        <i class="fas fa-truck"></i>
    <h2>Transfer Stock</h2>
    <p>Move stock to other warehouses</p>
  </div>
  
</body>
</html>